name: micardflutter
description: Information Card

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/i.jpg

  fonts:
    - family: Norican
      fonts:
        - asset: fonts/Norican-Regular.ttf

    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-VariableFont_wght.ttf

